# generated by datamodel-codegen:
#   filename:  v1/common/common.yaml
#   timestamp: 2025-06-12T09:53:19+00:00

from __future__ import annotations

from enum import Enum


class Connector(Enum):
    CLOUD_AZURE = 'cloud_azure'
    CLOUD_AWS = 'cloud_aws'
    PACKETFENCE = 'packetfence'
