# generated by datamodel-codegen:
#   filename:  v1/provider/inventory.yaml
#   timestamp: 2025-06-12T09:53:19+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field, RootModel

from ..common.inventory import InventoryItem, Label


class NetworkConnections(BaseModel):
    network: str
    reachable_networks: List[str] = Field(..., alias='reachable-networks')


class InventoryAssetType(Enum):
    VMS = 'vms'
    K8S_SERVICES = 'k8s_services'
    K8S_CONTROLLERS = 'k8s_controllers'
    K8S_CLUSTER = 'k8s_cluster'
    K8S_NODES = 'k8s_nodes'
    K8S_NAMESPACES = 'k8s_namespaces'


class InventoryReporterType(Enum):
    KUBERNETES = 'Kubernetes'


class NetworkTopology(RootModel[List[NetworkConnections]]):
    root: List[NetworkConnections]

    def __getattr__(self, attr: str):
        return getattr(self.root, attr)

    def __iter__(self):
        for item in self.root:
            yield item


class Labels(RootModel[List[Label]]):
    root: List[Label]

    def __getattr__(self, attr: str):
        return getattr(self.root, attr)

    def __iter__(self):
        for item in self.root:
            yield item


class Inventory(RootModel[List[InventoryItem]]):
    root: List[InventoryItem]

    def __getattr__(self, attr: str):
        return getattr(self.root, attr)

    def __iter__(self):
        for item in self.root:
            yield item
